### ISSUE TITLE
Speichermöglichkeit mittels XML

### ISSUE THREAD

**Issue by Luciddeft** [TGM-HIT/sew9-2324-worttrainer-manuthebyte#1]
**Beschreibung:**
Die derzeitige Version unserer Anwendung ermöglicht die Speicherung von Worttrainer-Sessions mithilfe von JSON und dem GSON-Framework. Dies bietet eine solide und flexible Methode zur Persistierung von Daten. Allerdings gibt es Situationen, in denen XML-Dateien bevorzugt werden, sei es aus Kompatibilitätsgründen oder aufgrund spezifischer Anforderungen.

**Problemstellung:**
Die aktuelle Implementierung unterstützt nur die Speicherung in JSON-Format. Einige Benutzer bevorzugen jedoch die Verwendung von XML-Dateien für ihre Daten oder benötigen sie aus anderen Gründen. Wir möchten daher eine zusätzliche Option hinzufügen, die es ermöglicht, Worttrainer-Sessions als XML-Dateien zu speichern.

**Vorgeschlagene Lösung:**
- [x] Erweiterung der Anwendung um die Möglichkeit, Worttrainer-Sessions als XML zu speichern und wiederherzustellen.
- [x] Implementierung eines neuen Interfaces oder einer Klasse (z. B. "XMLPersistMethod"), um die XML-Persistierung zu unterstützen.

**Akzeptanzkriterien:**
- [x] Die XML-Persistierungsmethode ist gut dokumentiert und einfach zu verwenden.
- [x] Die bestehenden Tests werden aktualisiert, um die neue Funktionalität abzudecken.
- [x] Es gibt keine unerwarteten Nebenwirkungen auf die bestehende Funktionalität der Anwendung.

**Comment by manuthebyte** [comment]
Welche spezifischen Anforderungen oder Gründe gibt es, warum einige Benutzer XML gegenüber JSON bevorzugen? Gibt es bestimmte Szenarien, in denen XML unverzichtbar ist?

**Comment by Luciddeft** [comment]
Die Hauptgründe sind vor allem Kompatibilität mit anderen Systemen, die XML verwenden, und die Möglichkeit, Daten in einer hierarchischen Struktur zu speichern. Einige Benutzer müssen möglicherweise vorhandene XML-Systeme integrieren oder haben persönliche Vorlieben für XML.

**Comment by manuthebyte** [comment]
Verstehe ich das jetzt richtig, dass du vorschlägst, eine zusätzliche Option für die Speicherung von Worttrainer-Sessions als XML hinzuzufügen, aber die bestehende JSON-Speicherung beizubehalten?

**Comment by Luciddeft** [comment]
Genau, das ist korrekt. Die Idee ist, die Flexibilität unserer Anwendung zu erhöhen.

**Comment by manuthebyte** [comment]
Wie beabsichtigst du, dass wir die XML-Persistierung implementieren? Gibt es bestimmte Libraries oder Technologien, die du verwenden möchtest?

**Comment by Luciddeft** [comment]
Ich denke, wir könnten die Java XML-Verarbeitungsbibliotheken verwenden, um die XML-Persistierung zu realisieren. Wir sollten auch sicherstellen, dass die neue XML-Persistierungsmethode gut dokumentiert ist.

**Comment by manuthebyte** [comment]
Perfekt, danke! Ich denke, ich habe eine gute Vorstellung davon, was zu tun ist. Ich werde direkt daran arbeiten und dich dann updaten.
